### ISSUE TITLE
Dataset Config Name in KEDataArguments

### ISSUE THREAD

**Issue by debanjanbhucs** [midas-research/dlkp#16]
`dataset_config_name="extraction",`

Do we need this in the KEDataArguments? What if someone enters generation? 'extraction' should be fixed and the users should not be able to change that.

**Comment by ad6398** [comment]
Hey @debanjanbhucs, this is an optional argument and by default, its value is `extraction`. This option is still provided to users in the case a user might want to use a different dataset that has a different `dataset_config_name`.

**Comment by ad6398** [comment]
closing this for now, feel free to re-open @debanjanbhucs
