### ISSUE TITLE
Unable to select the free gpu while training

### ISSUE THREAD

**Issue by debanjanbhucs** [midas-research/dlkp#17]
Currently the training code does not select the free gpu while training the models. If trained on a multi gpu system if one of the GPUs is busy (GPU:0) it does not select the other GPU (GPU:1), it would be nice to have that feature.

**Comment by ad6398** [comment]
Hey @debanjanbhucs, GPU selection and visibility should be controlled by the user end, we can't provide that functionality somewhere in our scripts. pls [refer to this](https://huggingface.co/docs/transformers/main_classes/trainer#specific-gpus-selection) for detailed info from hugging face. User needs to set the `CUDA_VISIBLE_DEVICES` and `CUDA_DEVICE_ORDER` variable in their environments.

**Comment by ad6398** [comment]
@debanjanbhucs pls re-open if you want to discuss this point again
