### ISSUE TITLE
get_predicted_labels in KEDatasets

### ISSUE THREAD

**Issue by debanjanbhucs** [midas-research/dlkp#22]
What is the use of the method

```
    def get_predicted_labels(self, predictions):
        self.datasets = "g"

```

https://github.com/midas-research/dlkp/blob/main/src/dlkp/datasets/extraction.py#L155

**Comment by ad6398** [comment]
@debanjanbhucs this is not required, I forgot to remove this. Let me create a PR

**Comment by ad6398** [comment]
@debanjanbhucs fixed
