### ISSUE TITLE
tmp_trainer directory getting created after running the training

### ISSUE THREAD

**Issue by debanjanbhucs** [midas-research/dlkp#23]
`tmp_trainer` directory is automatically getting created while running training. The directory is created in the same path in which the training script is being invoked.

**Comment by ad6398** [comment]
hey, @debanjanbhucs this is expected behaviour from hugging face, pls [refer to this](https://huggingface.co/transformers/v3.5.1/main_classes/trainer.html#transformers.Trainer). This folder is meant to save statistics during inference. In future, we can use it to store queries and their keyphrases.

**Comment by debanjanbhucs** [comment]
Ok! In that case if we change the output_dir this should not get created. Will try out and then close this.
